make file fonctionnelle

diff --git a/completion-system/Makefile b/completion-system/Makefile
--- a/completion-system/Makefile
+++ b/completion-system/Makefile
@@ -7,12 +7,14 @@ DESKTOP_FILE := ~/.local/share/applications/$(APP_NAME).desktop
 install: setup udev build move_binary install_desktop update_groups
 
 setup:
+	@echo ""
 	@echo "Updating system and installing dependencies..."
 	@sudo apt update
-	@sudo apt install -y cargo libudev-dev pkg-config python3 python3-tk
+	@sudo apt install -y libudev-dev pkg-config python3 python3-tk
 	@sudo usermod -aG input $(USERNAME)
 
 udev:
+	@echo ""
 	@echo "Configuring udev rules..."
 	@if ! grep -q 'KERNEL=="uinput", OWNER="$(USERNAME)", MODE="600"' /etc/udev/rules.d/99-uinput-completion-system.rules; then \
 		echo 'KERNEL=="uinput", OWNER="$(USERNAME)", MODE="600"' | sudo tee -a /etc/udev/rules.d/99-uinput-completion-system.rules; \
@@ -23,10 +25,16 @@ udev:
 	fi
 
 build:
-	@echo "Building project..."
-	@cargo build --release || { echo "Build failed"; exit 1; }
+	@if [ ! -f ./target/release/$(APP_NAME) ]; then \
+		@echo "" ; \
+		echo "Install cargo..."; \
+		sudo apt install -y cargo; \
+		echo "Building project..."; \
+		cargo build --release || { echo "Build failed"; exit 1; }; \
+	fi	
 
 run:
+	@echo ""
 	@echo "Running the executable..."
 	@if [ -f ./target/release/$(APP_NAME) ]; then \
 		./target/release/$(APP_NAME); \
@@ -36,6 +44,7 @@ run:
 	fi
 
 move_binary:
+	@echo ""
 	@echo "Moving binary to /usr/local/bin..."
 	@if [ -f ./target/release/$(APP_NAME) ]; then \
 		if [ -f $(BIN_PATH) ]; then \
@@ -50,6 +59,7 @@ move_binary:
 	fi
 
 install_desktop:
+	@echo ""
 	@echo "Installing desktop entry and icon..."
 	@if [ ! -f $(DESKTOP_FILE) ]; then \
 		echo "[Desktop Entry]" > $(DESKTOP_FILE); \
@@ -71,15 +81,18 @@ install_desktop:
 	fi	
 
 update_groups:
+	@echo ""
 	@echo "Updating input group..."
-	@newgrp input
+	newgrp input
 
 clean:
+	@echo ""
 	@echo "Cleaning up build files..."
 	@rm -rf target
 	@echo "Build files removed."
 
 uninstall:
+	@echo ""
 	@echo "Uninstalling binary..."
 	@if [ -f $(BIN_PATH) ]; then \
 		sudo rm $(BIN_PATH); \
@@ -97,7 +110,7 @@ uninstall:
 		echo "uinput rules do not exist."; \
 	fi
 
-	@echo "Removing desktop entry and icon..."
+	echo "Removing desktop entry and icon..."
 	@if [ -f $(DESKTOP_FILE) ]; then \
 		rm $(DESKTOP_FILE); \
 		echo "Desktop entry removed."; \
